language: node_js
node_js:
  - "8"
dist: trusty
sudo: false

cache:
  directories:
    - node_modules

addons:
  chrome: stable

script:
  - npm install
  - cd .\AngularUI\
  - sudo npm install -g @angular/cli
  - ng build