language: node_js
node_js:
  - "9"
dist: trusty
sudo: required

branches:
  only:
  - master

before_script:
  - cd AngularUI
  - npm install -g @angular/cli
  - ng update
  - npm update
  - npm install -g firebase-tools

script:
  - ng build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN